version: "3"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    network_mode: host

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=scm
      - DOCKER_INFLUXDB_INIT_PASSWORD=scm_admin123
      - DOCKER_INFLUXDB_INIT_ORG=scm
      - DOCKER_INFLUXDB_INIT_BUCKET=scm_monitoring
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - influxdb-config:/etc/influxdb
    network_mode: host
volumes:
  grafana-storage: {}
  influxdb-storage: {}
  influxdb-config: {}
