version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prom
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    network_mode: host
    # networks:
    #   - scm-monitor
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    network_mode: host

volumes:
  grafana-storage: {}